### ISSUE TITLE
SendMessage: object WebSocket not found!

### ISSUE THREAD

**Issue by Chunmei12** [y85171642/UnityWebSocket#1]
hello, 
  when i running webgl on the node server.  he can connect the server, but when i prepare to send or receive messages, the webgl console always show the info:  "SendMessage: object WebSocket not found!"
I don't known why and I have bloc here for a long time.  thank you for response.

**Comment by y85171642** [comment]
Year i got your  message




On 08/02/2017 22:25, Chunmei12 wrote:

hello,
when i running webgl on the node server. he can connect the server, but when i prepare to send or receive messages, the webgl console always show the info: "SendMessage: object WebSocket not found!"
I don't known why and I have bloc here for a long time. thank you for response.

**Comment by y85171642** [comment]
you need a gameobject named with WebSocket and add a WebSocket component




On 08/31/2017 08:50, 殷龙 wrote:
Year i got your  message




On 08/02/2017 22:25, Chunmei12 wrote:

hello,
when i running webgl on the node server. he can connect the server, but when i prepare to send or receive messages, the webgl console always show the info: "SendMessage: object WebSocket not found!"
I don't known why and I have bloc here for a long time. thank you for response.

**Comment by y85171642** [comment]
@Chunmei12 
See the class WebSocketManager
    /// <summary>
    /// <para>This component must add to a GameObject will not be destroyed. </para>
    /// <para>And make sure the GameObject Named with WebSocket.</para>
    /// <para>Cause of Unity will SendMessage to it when receive messages.</para>
    /// <para>需要挂在不会被销毁的GameObject上，</para>
    /// <para>并且保证GameObject的名字为WebSocket，</para>
    /// <para>因为接收消息时候Unity会SendMessage给它。</para>
    /// </summary>
