### ISSUE TITLE
这个库好像不支持wss://协议，建立连接直接就抛异常了

### ISSUE THREAD

**Issue by richfuns** [y85171642/UnityWebSocket#10]
如标题，请教作者有没这个问题

**Comment by y85171642** [comment]
哦，还真没注意这个问题，我测试下，多谢提醒

**Comment by richfuns** [comment]
> 哦，还真没注意这个问题，我测试下，多谢提醒

谢谢，麻烦你测一下看看

**Comment by y85171642** [comment]
> > 哦，还真没注意这个问题，我测试下，多谢提醒
> 
> 谢谢，麻烦你测一下看看

哈喽，刚提交了1.2.2版本，可以帮忙测试下，是否支持 wss 协议吗？因为我这边还没有服务器的授权签名文件，一直没法测试。

**Comment by richfuns** [comment]
> > > 哦，还真没注意这个问题，我测试下，多谢提醒
> > 
> > 
> > 谢谢，麻烦你测一下看看
> 
> 哈喽，刚提交了1.2.2版本，可以帮忙测试下，是否支持 wss 协议吗？因为我这边还没有服务器的授权签名文件，一直没法测试。

好，我测下，我这边有个服务器

**Comment by y85171642** [comment]
v1.2.2以上版本已经支持 wss协议
