### ISSUE TITLE
求教这个库如何正确的配置wss? 谢谢

### ISSUE THREAD

**Issue by richfuns** [y85171642/UnityWebSocket#11]
服务器提供了1个xxx.cert文件，一个xxx.key结尾的文件

客户端这块该如何配置呢？ 谢谢

**Comment by y85171642** [comment]
只有服务器需要配置这些文件吧，客户端一般是不需要配置的，服务器配置的话，参考 [websocket-sharp](https://github.com/sta/websocket-sharp) 插件 wss 配置方法。

**Comment by richfuns** [comment]
谢谢回复， sharp上面提示这样配置

Secure Connection
websocket-sharp supports the secure connection with SSL/TLS.

As a WebSocket client, you should create a new instance of the WebSocket class with a wss scheme WebSocket URL.

var ws = new WebSocket ("wss://example.com");
If you would like to set a custom validation for the server certificate, you should set the WebSocket.SslConfiguration.ServerCertificateValidationCallback property to a callback for it.

ws.SslConfiguration.ServerCertificateValidationCallback =
  (sender, certificate, chain, sslPolicyErrors) => {
    // Do something to validate the server certificate.
    ...

    return true; // If the server certificate is valid.
  };
The default callback always returns true.

As a WebSocket server, you should create a new instance of the WebSocketServer or HttpServer class with some settings for the secure connection, such as the following.

var wssv = new WebSocketServer (5963, true);
wssv.SslConfiguration.ServerCertificate =
  new X509Certificate2 ("/path/to/cert.pfx", "password for cert.pfx");

我暂时先这样配，还没有跟后台测试到底行不行
