### ISSUE TITLE
请教作者这个库能否实现SSL Websocket双向认证? 

### ISSUE THREAD

**Issue by richfuns** [y85171642/UnityWebSocket#12]
多谢指教。

**Comment by y85171642** [comment]
客户端的验证，写在这里：
https://github.com/sta/websocket-sharp#secure-connection
需自行修改源码
暂时只支持非WebGL平台。

**Comment by richfuns** [comment]
> 客户端的验证，写在这里：
> https://github.com/sta/websocket-sharp#secure-connection
> 需自行修改源码
> 暂时只支持非WebGL平台。

谢谢，这里看过了，源码已做了修改，目前还没测试，是支持ssl的,  但是我不确定是不是双向认证哈。
