### ISSUE TITLE
最后一次发包，2分钟后整会自动断开连接，哪里能屏蔽掉这个自动关闭连接呢?

### ISSUE THREAD

**Issue by BuKuSiShen** [y85171642/UnityWebSocket#13]
![图片](https://user-images.githubusercontent.com/12295354/70766806-e8bb1d00-1d99-11ea-9ab4-c614844645ab.png)

**Comment by y85171642** [comment]
我这边测试，并没有自动断连的情况，而且底层没有设置自动断连的逻辑。可能是你连接到的服务器有做一些特殊处理，或者你可以用echo服务器测试下有没有自动断连的问题：  
 wss://demos.kaazing.com/echo
  ws://demos.kaazing.com/echo

**Comment by BuKuSiShen** [comment]
@y85171642 谢谢作者回复，我刚才也连demo里的线上服务器测试了，7分钟还保持着连接，那应该是我们服务器的问题了

**Comment by y85171642** [comment]
不客气，那我关闭Issue了
