### ISSUE TITLE
能连接，不能发送数据。

### ISSUE THREAD

**Issue by zwluoqi** [y85171642/UnityWebSocket#3]
如题，使用环境是2017.1.3。平台：WebGL

**Comment by y85171642** [comment]
没有报错吗？能具体描述下现象吗？或者打个package给我，我测试下，麻烦了~
我QQ 799329256

**Comment by y85171642** [comment]
@zwluoqi 亲亲，再不回复，我就要关闭问题了哦

**Comment by y85171642** [comment]
@zwluoqi 亲亲，再不回复，我就要关闭问题了哦

**Comment by zwluoqi** [comment]
嗯嗯 好的。
