### ISSUE TITLE
请问这个库有没有解决粘包，分包的问题呢？

### ISSUE THREAD

**Issue by richfuns** [y85171642/UnityWebSocket#4]
偶然发现这个库，很不错，准备使用一下呢

**Comment by richfuns** [comment]
@y85171642 谢谢回复，您这个库使用的是标准的Websocket吗？ 
我们之前用的是js 标准websocket 倒是没碰到过有分包，粘包的问题

**Comment by y85171642** [comment]
嗯嗯，打包WebGL平台，执行的就是js的websocket
打包其他平台，使用的是websocket-sharp插件
我觉得粘包的问题应该是都不会出现，半包的问题有可能会出现，具体我要测试下，没问题的话，再给你答复哦。 @richfuns

**Comment by richfuns** [comment]
@y85171642  导入后，有警告，不知大神有没有发现哦
![default](https://user-images.githubusercontent.com/1400999/45078624-0f17f480-b123-11e8-9896-0905e9935496.png)

我是Unity 2018.2.4

**Comment by y85171642** [comment]
@richfuns  这个警告我这边也有，是websocket-sharp插件的警告，应该没关系的，我后面在更新下最新的websocket-sharp插件试试，
还有，2018 版本支持WebAssembly打包方式了，据说效率更快，包更小，可以试试哦~
