### ISSUE TITLE
请教：如果后台都是以string的格式给client发送json数据，用这个组件该怎么接收呢？

### ISSUE THREAD

**Issue by richfuns** [y85171642/UnityWebSocket#5]
大致看了下代码，WebSocket.cs中定义的只接受byte[]格式

`        public Action<byte[]> onReceive { get; set; }`

调用的是MessageEventArgs.cs文件中的代码

`    public byte[] RawData {
      get {
        setData ();
        return _rawData;
      }
    }`

如果服务器给client都以string的形式发送json数据，请教该怎么接收数据呢？（同理： client也会直接发送string给服务器端）

谢谢大神们！

**Comment by richfuns** [comment]
@y85171642  你好，大神，我的意思是我们服务器是直接发送的string到client，并不是byte[]

Demo 中这个方法好像只能接受byte[]

`     private void OnReceive(byte[] data)
        {
            content += "[RECEIVE] " + System.Text.Encoding.UTF8.GetString(data) + "\n";
        }`

哪个方法可以直接接收字符串呢？

**Comment by y85171642** [comment]
哦，没写接收string 的方法，我回头加一个

**Comment by y85171642** [comment]
@ @richfuns 今晚我加，别急

**Comment by richfuns** [comment]
@y85171642 多谢大神，写好了麻烦回复下哈，我这边着急用，有点。哈哈。不好意思-

**Comment by y85171642** [comment]
@richfuns  Hello  可以切换到develop分支上，重构了事件处理，规范成统一的WebSocket方式，之后会发一个Release 版本到master上！

**Comment by y85171642** [comment]
@richfuns  哦对，我加了string 类型的发送与接收了，用法参考Example

**Comment by richfuns** [comment]
@y85171642 非常感谢，太敬业了，小弟佩服，我先下载开发分支的看下，这么好的库，期待能持续维护下去啊

**Comment by y85171642** [comment]
@richfuns  v1.2.0 版本已发，[可以下载最新的了](https://github.com/y85171642/UnityWebSocket/releases)，该也问题准备关闭了！

**Comment by richfuns** [comment]
@y85171642 支持，支持，我先测试下看看有没啥问题

**Comment by y85171642** [comment]
@richfuns  好的，有问题，或者修改意见，留言我~

**Comment by richfuns** [comment]
@y85171642 好，谢谢大神，麻烦多多指教哈
