### ISSUE TITLE
求教Socket事件回调默认都在非UI线程，怎么在UI线程更新Unity UI呢？请教思路，谢谢

### ISSUE THREAD

**Issue by richfuns** [y85171642/UnityWebSocket#8]
介绍说：需要在主线程中加消息处理队列（需要加锁），缓存网络消息后，再在主线程中处理消息包。

请教具体实现方式？ 或者demo 

非常感谢

**Comment by y85171642** [comment]
参考这里：https://github.com/y85171642/XiaoGame_New/blob/master/Client/Assets/Scripts/Manager/NetworkManager.cs
这个就不要了提Issue 了

**Comment by y85171642** [comment]
> 
> 
> 介绍说：需要在主线程中加消息处理队列（需要加锁），缓存网络消息后，再在主线程中处理消息包。
> 
> 请教具体实现方式？ 或者demo
> 
> 非常感谢

`            private object m_lockTag = new object();
            private Queue<object> m_msgQueue = new Queue<object>();
            private bool m_triggerConnected = false;
            private bool m_triggerClosed = false;

            protected override void OnReceivedHandle(object data)
            {
                lock (m_lockTag)
                {
                    m_msgQueue.Enqueue(data);
                }
            }

            protected override void OnConnected()
            {
                lock (m_lockTag)
                {
                    m_triggerConnected = true;
                }
            }

            protected override void OnClosed()
            {
                lock (m_lockTag)
                {
                    m_triggerClosed = true;
                }
            }


            public void Update()
            {
                HandlePoolMsg();
            }

            private void HandlePoolMsg()
            {
                lock (m_lockTag)
                {
                    while (m_msgQueue.Count > 0)
                    {
                        var obj = m_msgQueue.Dequeue();
                        m_eventMgr.Send(obj.GetType().Name, obj);
                    }

                    if (m_triggerConnected)
                    {
                        base.OnConnected();
                        m_triggerConnected = false;
                    }

                    if (m_triggerClosed)
                    {
                        base.OnClosed();
                        m_triggerClosed = false;
                    }
                }
}`
