### ISSUE TITLE
求指教： 打开或关闭socket, 都会报一个错误，经常出现这个问题

### ISSUE THREAD

**Issue by richfuns** [y85171642/UnityWebSocket#9]
**打开报错如下：**

```
Socket onError: An error has occurred during the OnOpen event.
UnityWebSocket.WebSocket:<WebSocket>m__2(Object, ErrorEventArgs) (at UnityWebSocket/WebSocket.cs:112)
WebSocketSharp.Ext:Emit(EventHandler`1, Object, ErrorEventArgs) (at UnityWebSocket/websocket-sharp/Ext.cs:1254)
WebSocketSharp.WebSocket:error(String, Exception) (at UnityWebSocket/websocket-sharp/WebSocket.cs:1421)
WebSocketSharp.WebSocket:open() (at UnityWebSocket/websocket-sharp/WebSocket.cs:1537)
WebSocketSharp.WebSocket:Connect() (at UnityWebSocket/websocket-sharp/WebSocket.cs:3241)
UnityWebSocket.WebSocket:Connect() (at UnityWebSocket/WebSocket.cs:123)
```

**关闭报错如下：**

```
Socket onError: An error has occurred during the OnClose event.
UnityWebSocket.WebSocket:<WebSocket>m__2(Object, ErrorEventArgs) (at UnityWebSocket/WebSocket.cs:112)
WebSocketSharp.Ext:Emit(EventHandler`1, Object, ErrorEventArgs) (at UnityWebSocket/websocket-sharp/Ext.cs:1254)
WebSocketSharp.WebSocket:error(String, Exception) (at UnityWebSocket/websocket-sharp/WebSocket.cs:1421)
WebSocketSharp.WebSocket:close(PayloadData, Boolean, Boolean, Boolean) (at UnityWebSocket/websocket-sharp/WebSocket.cs:1140)
WebSocketSharp.WebSocket:close(UInt16, String) (at UnityWebSocket/websocket-sharp/WebSocket.cs:1094)
WebSocketSharp.WebSocket:Close() (at UnityWebSocket/websocket-sharp/WebSocket.cs:2566)
UnityWebSocket.WebSocket:Close() (at UnityWebSocket/WebSocket.cs:143)
```

虽然第一次打开连接会报错，不过最后OnOpen走了两次，第二次能连接成功

```
 private void OnOpen(object sender, EventArgs e)
        {
            Debug.Log("Socket Connected");
        }
```

**Comment by y85171642** [comment]
OK，我查一下

**Comment by richfuns** [comment]
> OK，我查一下

感谢感谢，元旦快乐！！

我也在查哪里问题，因为第一次socket连接比较慢，需要3-4秒，就在想是不是这个问题导致的，退出场景再进入，连接socket就非常快，不知道是不是有啥缓存之类的

**Comment by y85171642** [comment]
我这边并不能复现这个问题，你可以把断点加 websocket-sharp/WebSocket.cs  1536 行，看下具体的exception 是什么。
或者修改 websocket-sharp 的logLevel等级，并注册 log output 回调，看看打印出来的exception 内容。

**Comment by richfuns** [comment]
> 我这边并不能复现这个问题，你可以把断点加 websocket-sharp/WebSocket.cs 1536 行，看下具体的exception 是什么。
> 或者修改 websocket-sharp 的logLevel等级，并注册 log output 回调，看看打印出来的exception 内容。

非常感谢，找到问题了，回调函数爆了  System.NullReferenceException异常，是我自己的原因。抱歉

另外请教一下，所有的socket方法应该用异步的，还是同步的呢？ 比如
socket.Send（）
socket.SendAsync( )
......

如果都用异步的，走的回调函数应该都一样吧？

**Comment by y85171642** [comment]
尽量用同步的吧，现在webgl下还不支持异步，其他平台可以使用异步。
SendAsync 异步回调，需要的话可以注册，不需要 completed 为空 即可。

**Comment by richfuns** [comment]
> 尽量用同步的吧，现在webgl下还不支持异步，其他平台可以使用异步。
> SendAsync 异步回调，需要的话可以注册，不需要 completed 为空 即可。

晕，刚刚都换成异步了，貌似没啥问题，webgl应该是H5平台的吧？未来的版本有没有可能支持H5呢？

再次感谢

**Comment by y85171642** [comment]
> 
> 
> > 尽量用同步的吧，现在webgl下还不支持异步，其他平台可以使用异步。
> > SendAsync 异步回调，需要的话可以注册，不需要 completed 为空 即可。
> 
> 晕，刚刚都换成异步了，貌似没啥问题，webgl应该是H5平台的吧？未来的版本有没有可能支持H5呢？
> 
> 再次感谢

WebGL平台下，SendAsync 调用的还是同步 发送，所以使用上应该是没什么问题的，由于H5下暂时不支持异步WebSocket操作，所以现阶段只能用同步方式。（PS：上层可以统一都用异步）

**Comment by richfuns** [comment]
> > > 尽量用同步的吧，现在webgl下还不支持异步，其他平台可以使用异步。
> > > SendAsync 异步回调，需要的话可以注册，不需要 completed 为空 即可。
> > 
> > 
> > 晕，刚刚都换成异步了，貌似没啥问题，webgl应该是H5平台的吧？未来的版本有没有可能支持H5呢？
> > 再次感谢
> 
> WebGL平台下，SendAsync 调用的还是同步 发送，所以使用上应该是没什么问题的，由于H5下暂时不支持异步WebSocket操作，所以现阶段只能用同步方式。（PS：上层可以统一都用异步）

明白了，感谢宝贵建议。膜拜大神。。。！！！
